<?php

namespace App\Models;

use App\Models\Scopes\StopGradeScope;
use Backpack\CRUD\app\Models\Traits\CrudTrait;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class StopGrade extends Grade
{
    use HasFactory;
    use CrudTrait;

    protected $table = "grades";
    protected $guarded = ['id'];
    // protected $fillable = [];
    // protected $hidden = [];
    // protected $dates = [];
    protected $casts = [
        'time' => 'array'
    ];

    protected static function boot()
    {
        parent::subBoot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new StopGradeScope);
    }
}
